version: '3.9'

services:
  db_server:
    image: mysql:latest
    container_name: db_server
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1593572846
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    networks:
      - my_network

  sites_ativos:
    container_name: sites_ativos_2_0
    build:
      context: ./Python/sites_ativos_2_0
    ports:
      - "8000:8000"
    platform: linux/x86_64
    depends_on:
      db_server:
        condition: service_healthy
    image: python:3.8.5
    working_dir: /sites_ativos_2_0
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8000"]
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - my_network

networks:
  my_network:
