def login(driver, By, Keys, time, login, senha):

    time.sleep(1)
    input_text = driver.find_element(By.XPATH, "//input[@type='text']")
    time.sleep(1)
    input_text.send_keys(login)
    time.sleep(1)
    input_text.send_keys(Keys.TAB)
    time.sleep(1)
    input_senha = driver.find_element(By.XPATH, "//input[@type='password']")
    time.sleep(1)
    input_senha.send_keys(senha)
    time.sleep(1)
    send = driver.find_element(By.XPATH, "//button[@type='submit']")
    time.sleep(1)
    send.click()
    time.sleep(10)
    driver.find_element(By.PARTIAL_LINK_TEXT, "Bojnice Castle").click()
    time.sleep(10)
    print("Logado com sucesso!")
